### ISSUE TITLE
Cover Art is not displayed in Media Notification

### ISSUE THREAD

**Issue by NotoriousNico** [flathub/ca.edestcroix.Recordbox#6]
Hi,

Sorry for opening yet another issue, just after you closed my previous one the day before.
I've encountered a small issue with Recordbox 0.9.0:

The Cover Art is not displayed inside the Media Notification.
Here's what it looks like on my PC running Ubuntu 24.10 with GNOME 47:
![image](https://github.com/user-attachments/assets/50bd4fa3-109f-4d8e-91f9-b3e38f74db7e)

And here's how it looks like in Tauon:
![Screenshot From 2024-12-22 10-02-26](https://github.com/user-attachments/assets/5dd9f518-e5cb-4285-8c08-b578570e30ff)

I'm not sure if this is a bug or intended behavior, because I don't know if Recordbox actually transmits Cover Art to the Media Notification. In any case, it would be nice to have.

As for my setup: My Cover Art is embedded inside the metadata of my music files (mostly FLAC files).
Please let me know if you need any more information or data from me.

**Comment by edestcroix** [comment]
Hi, no worries. It's a problem I was working on, by I had to focus on things other than Recordbox for a while so I took a break and ended up forgetting about it when I came back, so thanks for the reminder. I have mostly external cover files so I might not have noticed for a while.

Basically, the MPRIS protocol for displaying that notification can only take file paths to images, so I can't provide image data directly. For embedded images this means I have to save the image somewhere and give that to MPRIS, but when I redid how the thumbnails are loaded for 0.9.0 it made it so I wasn't able to provide file paths to MPRIS anymore. What other players do is save the thumbnail for the playing track in a temporary location and give MPRIS the path, but when I tried that it wasn't working reliably for some reason, so I need to debug it some more before I release it. I'm not expecting it too be too complicated though, should be able to get it fixed for a 0.9.1 release

**Comment by NotoriousNico** [comment]
Thank you for your reply and the explanation on how Cover Art is actually being displayed. I find these technical aspects quite fascinating.

**Comment by edestcroix** [comment]
Ok, this should be fixed now, I'm rolling out 0.9.1 right now with the fix and some other small changes. Turns out the reason it wasn't working the first time I tried is because for some reason I have to save the temporary image file with a different filename for each different image otherwise it doesn't change in the notification. 


> Thank you for your reply and the explanation on how Cover Art is actually being displayed. I find these technical aspects quite fascinating.

Your welcome, I like explaining why problems are happening to because writing it out usually leads me to figure out how to fix them during the explanation. Helps me get my thoughts in order.

Thanks again!

**Comment by NotoriousNico** [comment]
Thank you, the cover is being displayed now.
However, I've noticed that it's very low-quality.

I'm using the [Media Controls extension](https://extensions.gnome.org/extension/4470/media-controls/) for GNOME, and this is how the cover art looks like when playing music with Recordbox:

![Screenshot From 2025-01-08 14-09-36](https://github.com/user-attachments/assets/9226d78e-e1eb-43f7-97a1-e083c2c51f8a)

And this is how it looks like when using Tauon:
![Screenshot From 2025-01-08 14-09-57](https://github.com/user-attachments/assets/c89cbb25-1df7-4967-bd58-3503cd427cc0)

Would it be possible to create a higher quality image file for the cover art?

**Comment by edestcroix** [comment]
Okay I'll switch that. I use two sizes of image and I picked the smaller size, but it should have been the bigger one.

Somethings not working with the translations right now too, so when I figure that out I'll release 0.9.2 with that fix and I'll fix the cover resolution at the same time.

**Comment by NotoriousNico** [comment]
Great, thank you. I hope you can figure out the translation error. 🙂

**Comment by NotoriousNico** [comment]
@edestcroix Thank you for updating Recordbox to 0.9.2. The Cover Art looks better now, but it's still not quite there.

I've made two comparison screenshots for you.

**Tauon**
![Screenshot From 2025-01-16 08-55-19](https://github.com/user-attachments/assets/52cb44b6-8cb5-4398-9fde-8b3ddabb43fa)

**Recordbox**
![Screenshot From 2025-01-16 08-55-02](https://github.com/user-attachments/assets/78a28208-76ce-4e80-9a19-05145177c66c)

As you can see, Tauon provides a higher quality image.
The Cover Art also gets vertically stretched with Recordbox. Probably because the Cover Art doesn't have a 1:1 aspect ratio.

If it's not too much to ask: Could you please have another look?

Here's also the Cover Art from my screenshots, in case you need it:
![cover](https://github.com/user-attachments/assets/f00a31ba-c3fa-43bb-a5fe-987afded1143)

**Comment by edestcroix** [comment]
Interesting, was the quality of the images higher before the 0.9.0 update? I must have changed the way the images are handled more than I thought if that's the case. 

Also are the images embedded in the files the only images you have, or do you also have separate images files for albums? I changed the priority of which images are loaded so MPRIS now always gets the embedded ones, which might be lower quality and could be the reason, but it's probably just the down-scaling I'm doing. I can give MPRIS the full-size images instead, which I think should fix it. 

I'll make a test build when I have time to implement the fix that I can give you to test with the change so if it needs to be tweaked again I won't have to make more than one release. It'll probably be soon, although I've got more classes this term than the last one so I'm going to be busier with university the next few months compared to before, so it might be a bit longer between updates going forward.

**Comment by NotoriousNico** [comment]
I'm sorry, I can't tell if the quality was higher before 0.9.0, because I only started using the Media Controls extension recently.

As for where I store my cover art: All my cover art is embedded inside my music files and usually in a high quality.
Giving MPRIS the full-size images should fix the issue, because I think that's the same way Tauon does it.

And no rush with the test build, as this is just a minor visual imperfection. Take care of your studies first.
I appreciate all the time and effort you put into Recordbox.

**Comment by edestcroix** [comment]
Alright, I'm releasing 0.9.3 right now with the change to the resolution included. I ended up deciding not to do a test build and just release it because I won't have time to make adjustments if it's still blurry anyway, and then if does turn out to be good then it's already released.

Let me know how it looks and I can tweak it again if need be for 0.10.0, once I start working on it again.

**Comment by NotoriousNico** [comment]
Thank you for the update, 0.9.3 fixed my issue and everything looks crisp now:

![Image](https://github.com/user-attachments/assets/c6142f90-4322-4067-b984-f86bf0f8cbe2)
